sudo: required
services:
    - docker

before_install:
    - docker build -t dharmeshn007/docker-react -f Dockerfile.dev .

script:
    - docker run dharmeshn007/docker-react npm run test -- --coverage